version: "3.7"
services:
  fetcher-app:
    build: ./docker/otenki-fetcher
    depends_on:
      - db
    volumes:
      - ~/go/src/github.com/nachiguro1003/otenki/src/fetcher:/go/src/github.com/nachiguro1003/otenki/src/fetcher
    ports:
      - "8000:8000"
    command: tail -f /dev/null
  servicer-app:
    build: ./docker/otenki-servicer
    depends_on:
      - db
    volumes:
      - ~/go/src/github.com/nachiguro1003/otenki/src/servicer:/go/src/github.com/nachiguro1003/otenki/src/servicer
    ports:
      - "8001:8001"
    command: tail -f /dev/null
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otenki
    expose:
      - "5432"
    ports:
      - 5432:5432
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
  migration:
    image: gendosu/goose
    depends_on:
      - db
    volumes:
      - ~/go/src/github.com/nachiguro1003/otenki/db:/go/src/github.com/nachiguro1003/otenki/db
    ports:
      -  "8080:8080"
    command: tail -f /dev/null
  otenki-nginx:
    build: ./docker/nginx
    links:
      - servicer-app
    ports:
    - "80:80"
