apiVersion: v1
kind: Service
metadata:
  name: otenki-servicer
  labels:
    app: otenki-servicer
spec:
  selector:
    app: otenki-servicer
  ports:
    - name: http
      port: 80
      targetPort: 8001
  type: NodePort
